### ISSUE TITLE
delete-all-overlays not available in 24.2

### ISSUE THREAD

**Issue by milkypostman** [grizzl/grizzl#11]
just an FYI. not sure if it warrants a fix but I found this bug on a machine I only have 24.2 on.

**Comment by bbatsov** [comment]
I'll take a PR for this, but I won't pursue it actively (I'm super busy at work).

**Comment by milkypostman** [comment]
tbh, you can probably just close this. 24.2 is old.

i'm glad to see some recent life thrust into this.

**Comment by bbatsov** [comment]
:-)
