### ISSUE TITLE
Grizzl Display Error

### ISSUE THREAD

**Issue by nayefc** [grizzl/grizzl#26]
Hello,

I am using Fiplr (which I know uses Girzzl). I've posted this on Fiplr's issues page, but I did not get any responses. I am hoping that this is either a grizzl issue, or someone here could have faced it here.

I am using Emacs for OS X 24.4.1 on Yosemite. When the screen is not full screen, Fiplr doesn't show any results until I write enough to get a 1 or 2 matches. When I delete the searching text, it goes back to being empty.

When I use it on a 13-inch non-Retina MacBook Air display, it also does not work even on full-screen. This leads me to suspect that it depends on the screen size. Is there a reason for that? Why does fuzzy matching only work at some minimum screen size?

Thanks

**Comment by michaelbruce** [comment]
I am getting this issue too using grizzl with projectile, here's a copy/paste of the config I use to set this up.

(use-package projectile
  :defer t
  :diminish projectile-mode
  :commands (projectile-find-file-in-directory)
  :config
  (progn
    (use-package grizzl)
    (projectile-global-mode)
    (setq projectile-enable-caching t)
    (setq projectile-completion-system 'grizzl)))

will update this if I find a solution

**Comment by michaelbruce** [comment]
as a quick workaround, you can get the results to display by lowering the max number of results like this:

(setq *grizzl-read-max-results* 7)

**Comment by akshaal** [comment]
It seems like it depends upon the font size you use in emacs. I fixed the problem like this:
```
iff --git a/emacs/grizzl.el b/emacs/grizzl.el
index c0ecc5b..542e425 100644
--- a/emacs/grizzl.el
+++ b/emacs/grizzl.el
@@ -383,7 +383,7 @@ if this is the current selection."
             (propertize " "
                         'face    'modeline-inactive
                         'display `(space :align-to (- right
-                                                      ,(1+ (length match-info)))))
+                                                      ,(1+ (1+ (length match-info))))))
             (propertize match-info 'face 'modeline-inactive))))
 
 (defun grizzl-current-selection ()

```

otherwise modeline inside the grizzle buffer gets too long, wrapped and takes two lines instead of just one

**Comment by nayefc** [comment]
@akshaal I switched to Helm-Projectile a long time ago. Thanks though.
